version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
    - requirements:
        - sphinx>=3.0
        - sphinx-rtd-theme
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
