version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: . # Installs your main package
    - method: pip
      requirements: docs/requirements.txt # Correct key for requirements files

sphinx:
  configuration: docs/conf.py
