version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements: ["docs"] # If you have a docs extra in setup.py
    - method: pip
      path: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: []
