version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Correct python.install syntax
python:
  install:
    - method: pip
      path: . # Installs your package
    - method: pip
      path: docs/requirements.txt # Your docs requirements file

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optional: Formats to build
formats:
  - pdf
  - epub
