version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
    - method: pip
      path: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
