version: 2

build:
  os: ubuntu-22.04 # Updated to newer Ubuntu version
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: requirements.txt # Your main requirements
    - method: pip
      path: . # Install your package in editable mode
    - method: pip
      extra_requirements: # Correct way to specify direct packages
        - sphinx>=3.0
        - sphinx-rtd-theme

sphinx:
  configuration: docs/conf.py
