#!/usr/bin/env bash
# #!/bin/bash

../simulation.py --chi -10 --eigen_index 2 --time 5
../simulation.py --chi -9 --eigen_index 2 --time 5
../simulation.py --chi -8 --eigen_index 2 --time 5
../simulation.py --chi -7 --eigen_index 2 --time 5
../simulation.py --chi -6 --eigen_index 2 --time 5
../simulation.py --chi -5 --eigen_index 2 --time 5
../simulation.py --chi -4 --eigen_index 2 --time 5
../simulation.py --chi -3 --eigen_index 2 --time 5
../simulation.py --chi -2 --eigen_index 2 --time 5
../simulation.py --chi -1 --eigen_index 2 --time 5
../simulation.py --chi 0 --eigen_index 2 --time 5
../simulation.py --chi 1 --eigen_index 2 --time 5
../simulation.py --chi 2 --eigen_index 2 --time 5
../simulation.py --chi 3 --eigen_index 2 --time 5
../simulation.py --chi 4 --eigen_index 2 --time 5
../simulation.py --chi 5 --eigen_index 2 --time 5
../simulation.py --chi 6 --eigen_index 2 --time 5
../simulation.py --chi 7 --eigen_index 2 --time 5
../simulation.py --chi 8 --eigen_index 2 --time 5
../simulation.py --chi 9 --eigen_index 2 --time 5
../simulation.py --chi 10 --eigen_index 2 --time 5
../simulation.py --chi 11 --eigen_index 2 --time 5
../simulation.py --chi 12 --eigen_index 2 --time 5
../simulation.py --chi 13 --eigen_index 2 --time 5
../simulation.py --chi 14 --eigen_index 2 --time 5
../simulation.py --chi 15 --eigen_index 2 --time 5
../simulation.py --chi 16 --eigen_index 2 --time 5
../simulation.py --chi 17 --eigen_index 2 --time 5
../simulation.py --chi 18 --eigen_index 2 --time 5
../simulation.py --chi 19 --eigen_index 2 --time 5
../simulation.py --chi 20 --eigen_index 2 --time 5
../simulation.py --chi 21 --eigen_index 2 --time 5
../simulation.py --chi 22 --eigen_index 2 --time 5
../simulation.py --chi 23 --eigen_index 2 --time 5
../simulation.py --chi 24 --eigen_index 2 --time 5
../simulation.py --chi 25 --eigen_index 2 --time 5
../simulation.py --chi 26 --eigen_index 2 --time 5
../simulation.py --chi 27 --eigen_index 2 --time 5
../simulation.py --chi 28 --eigen_index 2 --time 5
../simulation.py --chi 29 --eigen_index 2 --time 5
../simulation.py --chi 30 --eigen_index 2 --time 5
../simulation.py --chi 31 --eigen_index 2 --time 5
../simulation.py --chi 32 --eigen_index 2 --time 5
../simulation.py --chi 33 --eigen_index 2 --time 5
../simulation.py --chi 34 --eigen_index 2 --time 5
../simulation.py --chi 35 --eigen_index 2 --time 5
../simulation.py --chi 36 --eigen_index 2 --time 5
../simulation.py --chi 37 --eigen_index 2 --time 5
../simulation.py --chi 38 --eigen_index 2 --time 5
../simulation.py --chi 39 --eigen_index 2 --time 5
../simulation.py --chi 40 --eigen_index 2 --time 5
../simulation.py --chi 41 --eigen_index 2 --time 5
../simulation.py --chi 42 --eigen_index 2 --time 5
../simulation.py --chi 43 --eigen_index 2 --time 5
../simulation.py --chi 44 --eigen_index 2 --time 5
../simulation.py --chi 45 --eigen_index 2 --time 5
../simulation.py --chi 46 --eigen_index 2 --time 5
../simulation.py --chi 47 --eigen_index 2 --time 5
../simulation.py --chi 48 --eigen_index 2 --time 5
../simulation.py --chi 49 --eigen_index 2 --time 5
../simulation.py --chi 50 --eigen_index 2 --time 5
../simulation.py --chi 51 --eigen_index 2 --time 5
../simulation.py --chi 52 --eigen_index 2 --time 5
../simulation.py --chi 53 --eigen_index 2 --time 5
../simulation.py --chi 54 --eigen_index 2 --time 5
../simulation.py --chi 55 --eigen_index 2 --time 5
../simulation.py --chi 56 --eigen_index 2 --time 5
../simulation.py --chi 57 --eigen_index 2 --time 5
../simulation.py --chi 58 --eigen_index 2 --time 5
../simulation.py --chi 59 --eigen_index 2 --time 5
../simulation.py --chi 60 --eigen_index 2 --time 5
../simulation.py --chi 61 --eigen_index 2 --time 5
../simulation.py --chi 62 --eigen_index 2 --time 5
../simulation.py --chi 63 --eigen_index 2 --time 5
../simulation.py --chi 64 --eigen_index 2 --time 5
../simulation.py --chi 65 --eigen_index 2 --time 5
../simulation.py --chi 66 --eigen_index 2 --time 5
../simulation.py --chi 67 --eigen_index 2 --time 5
../simulation.py --chi 68 --eigen_index 2 --time 5
../simulation.py --chi 69 --eigen_index 2 --time 5
../simulation.py --chi 70 --eigen_index 2 --time 5
../simulation.py --chi 71 --eigen_index 2 --time 5
../simulation.py --chi 72 --eigen_index 2 --time 5
../simulation.py --chi 73 --eigen_index 2 --time 5
../simulation.py --chi 74 --eigen_index 2 --time 5
../simulation.py --chi 75 --eigen_index 2 --time 5
../simulation.py --chi 76 --eigen_index 2 --time 5
../simulation.py --chi 77 --eigen_index 2 --time 5
../simulation.py --chi 78 --eigen_index 2 --time 5
../simulation.py --chi 79 --eigen_index 2 --time 5
../simulation.py --chi 80 --eigen_index 2 --time 5
../simulation.py --chi 81 --eigen_index 2 --time 5
../simulation.py --chi 82 --eigen_index 2 --time 5
../simulation.py --chi 83 --eigen_index 2 --time 5
../simulation.py --chi 84 --eigen_index 2 --time 5
../simulation.py --chi 85 --eigen_index 2 --time 5
../simulation.py --chi 86 --eigen_index 2 --time 5
../simulation.py --chi 87 --eigen_index 2 --time 5
../simulation.py --chi 88 --eigen_index 2 --time 5
../simulation.py --chi 89 --eigen_index 2 --time 5
../simulation.py --chi 90 --eigen_index 2 --time 5
../simulation.py --chi 91 --eigen_index 2 --time 5
../simulation.py --chi 92 --eigen_index 2 --time 5
../simulation.py --chi 93 --eigen_index 2 --time 5
../simulation.py --chi 94 --eigen_index 2 --time 5
../simulation.py --chi 95 --eigen_index 2 --time 5
../simulation.py --chi 96 --eigen_index 2 --time 5
../simulation.py --chi 97 --eigen_index 2 --time 5
../simulation.py --chi 98 --eigen_index 2 --time 5
../simulation.py --chi 99 --eigen_index 2 --time 5
../simulation.py --chi 100 --eigen_index 2 --time 5
../simulation.py --chi 101 --eigen_index 2 --time 5
../simulation.py --chi 102 --eigen_index 2 --time 5
../simulation.py --chi 103 --eigen_index 2 --time 5
../simulation.py --chi 104 --eigen_index 2 --time 5
../simulation.py --chi 105 --eigen_index 2 --time 5
../simulation.py --chi 106 --eigen_index 2 --time 5
../simulation.py --chi 107 --eigen_index 2 --time 5
../simulation.py --chi 108 --eigen_index 2 --time 5
../simulation.py --chi 109 --eigen_index 2 --time 5
../simulation.py --chi 110 --eigen_index 2 --time 5
../simulation.py --chi 111 --eigen_index 2 --time 5
../simulation.py --chi 112 --eigen_index 2 --time 5
../simulation.py --chi 113 --eigen_index 2 --time 5
../simulation.py --chi 114 --eigen_index 2 --time 5
../simulation.py --chi 115 --eigen_index 2 --time 5
../simulation.py --chi 116 --eigen_index 2 --time 5
../simulation.py --chi 117 --eigen_index 2 --time 5
../simulation.py --chi 118 --eigen_index 2 --time 5
../simulation.py --chi 119 --eigen_index 2 --time 5
../simulation.py --chi 120 --eigen_index 2 --time 5
../simulation.py --chi 121 --eigen_index 2 --time 5
../simulation.py --chi 122 --eigen_index 2 --time 5
../simulation.py --chi 123 --eigen_index 2 --time 5
../simulation.py --chi 124 --eigen_index 2 --time 5
../simulation.py --chi 125 --eigen_index 2 --time 5
../simulation.py --chi 126 --eigen_index 2 --time 5
../simulation.py --chi 127 --eigen_index 2 --time 5
../simulation.py --chi 128 --eigen_index 2 --time 5
../simulation.py --chi 129 --eigen_index 2 --time 5
../simulation.py --chi 130 --eigen_index 2 --time 5
../simulation.py --chi 131 --eigen_index 2 --time 5
../simulation.py --chi 132 --eigen_index 2 --time 5
../simulation.py --chi 133 --eigen_index 2 --time 5
../simulation.py --chi 134 --eigen_index 2 --time 5
../simulation.py --chi 135 --eigen_index 2 --time 5
../simulation.py --chi 136 --eigen_index 2 --time 5
../simulation.py --chi 137 --eigen_index 2 --time 5
../simulation.py --chi 138 --eigen_index 2 --time 5
../simulation.py --chi 139 --eigen_index 2 --time 5
../simulation.py --chi 140 --eigen_index 2 --time 5
../simulation.py --chi 141 --eigen_index 2 --time 5
../simulation.py --chi 142 --eigen_index 2 --time 5
../simulation.py --chi 143 --eigen_index 2 --time 5
../simulation.py --chi 144 --eigen_index 2 --time 5
../simulation.py --chi 145 --eigen_index 2 --time 5
../simulation.py --chi 146 --eigen_index 2 --time 5
../simulation.py --chi 147 --eigen_index 2 --time 5
../simulation.py --chi 148 --eigen_index 2 --time 5
../simulation.py --chi 149 --eigen_index 2 --time 5
../simulation.py --chi 150 --eigen_index 2 --time 5
../simulation.py --chi 151 --eigen_index 2 --time 5
../simulation.py --chi 152 --eigen_index 2 --time 5
../simulation.py --chi 153 --eigen_index 2 --time 5
../simulation.py --chi 154 --eigen_index 2 --time 5
../simulation.py --chi 155 --eigen_index 2 --time 5
../simulation.py --chi 156 --eigen_index 2 --time 5
../simulation.py --chi 157 --eigen_index 2 --time 5
../simulation.py --chi 158 --eigen_index 2 --time 5
../simulation.py --chi 159 --eigen_index 2 --time 5
../simulation.py --chi 160 --eigen_index 2 --time 5
../simulation.py --chi 161 --eigen_index 2 --time 5
../simulation.py --chi 162 --eigen_index 2 --time 5
../simulation.py --chi 163 --eigen_index 2 --time 5
../simulation.py --chi 164 --eigen_index 2 --time 5
../simulation.py --chi 165 --eigen_index 2 --time 5
../simulation.py --chi 166 --eigen_index 2 --time 5
../simulation.py --chi 167 --eigen_index 2 --time 5
../simulation.py --chi 168 --eigen_index 2 --time 5
../simulation.py --chi 169 --eigen_index 2 --time 5
../simulation.py --chi 170 --eigen_index 2 --time 5
../simulation.py --chi 171 --eigen_index 2 --time 5
../simulation.py --chi 172 --eigen_index 2 --time 5
../simulation.py --chi 173 --eigen_index 2 --time 5
../simulation.py --chi 174 --eigen_index 2 --time 5
../simulation.py --chi 175 --eigen_index 2 --time 5
../simulation.py --chi 176 --eigen_index 2 --time 5
../simulation.py --chi 177 --eigen_index 2 --time 5
../simulation.py --chi 178 --eigen_index 2 --time 5
../simulation.py --chi 179 --eigen_index 2 --time 5
../simulation.py --chi 180 --eigen_index 2 --time 5
../simulation.py --chi 181 --eigen_index 2 --time 5
../simulation.py --chi 182 --eigen_index 2 --time 5
../simulation.py --chi 183 --eigen_index 2 --time 5
../simulation.py --chi 184 --eigen_index 2 --time 5
../simulation.py --chi 185 --eigen_index 2 --time 5
../simulation.py --chi 186 --eigen_index 2 --time 5
../simulation.py --chi 187 --eigen_index 2 --time 5
../simulation.py --chi 188 --eigen_index 2 --time 5
../simulation.py --chi 189 --eigen_index 2 --time 5
../simulation.py --chi 190 --eigen_index 2 --time 5
../simulation.py --chi 191 --eigen_index 2 --time 5
../simulation.py --chi 192 --eigen_index 2 --time 5
../simulation.py --chi 193 --eigen_index 2 --time 5
../simulation.py --chi 194 --eigen_index 2 --time 5
../simulation.py --chi 195 --eigen_index 2 --time 5
../simulation.py --chi 196 --eigen_index 2 --time 5
../simulation.py --chi 197 --eigen_index 2 --time 5
../simulation.py --chi 198 --eigen_index 2 --time 5
../simulation.py --chi 199 --eigen_index 2 --time 5
../simulation.py --chi 200 --eigen_index 2 --time 5
../simulation.py --chi 201 --eigen_index 2 --time 5
../simulation.py --chi 202 --eigen_index 2 --time 5
../simulation.py --chi 203 --eigen_index 2 --time 5
../simulation.py --chi 204 --eigen_index 2 --time 5
../simulation.py --chi 205 --eigen_index 2 --time 5
../simulation.py --chi 206 --eigen_index 2 --time 5
../simulation.py --chi 207 --eigen_index 2 --time 5
../simulation.py --chi 208 --eigen_index 2 --time 5
../simulation.py --chi 209 --eigen_index 2 --time 5
../simulation.py --chi 210 --eigen_index 2 --time 5
../simulation.py --chi 211 --eigen_index 2 --time 5
../simulation.py --chi 212 --eigen_index 2 --time 5
../simulation.py --chi 213 --eigen_index 2 --time 5
../simulation.py --chi 214 --eigen_index 2 --time 5
../simulation.py --chi 215 --eigen_index 2 --time 5
../simulation.py --chi 216 --eigen_index 2 --time 5
../simulation.py --chi 217 --eigen_index 2 --time 5
../simulation.py --chi 218 --eigen_index 2 --time 5
../simulation.py --chi 219 --eigen_index 2 --time 5
../simulation.py --chi 220 --eigen_index 2 --time 5
../simulation.py --chi 221 --eigen_index 2 --time 5
../simulation.py --chi 222 --eigen_index 2 --time 5
../simulation.py --chi 223 --eigen_index 2 --time 5
../simulation.py --chi 224 --eigen_index 2 --time 5
../simulation.py --chi 225 --eigen_index 2 --time 5
../simulation.py --chi 226 --eigen_index 2 --time 5
../simulation.py --chi 227 --eigen_index 2 --time 5
../simulation.py --chi 228 --eigen_index 2 --time 5
../simulation.py --chi 229 --eigen_index 2 --time 5
../simulation.py --chi 230 --eigen_index 2 --time 5
../simulation.py --chi 231 --eigen_index 2 --time 5
../simulation.py --chi 232 --eigen_index 2 --time 5
../simulation.py --chi 233 --eigen_index 2 --time 5
../simulation.py --chi 234 --eigen_index 2 --time 5
../simulation.py --chi 235 --eigen_index 2 --time 5
../simulation.py --chi 236 --eigen_index 2 --time 5
../simulation.py --chi 237 --eigen_index 2 --time 5
../simulation.py --chi 238 --eigen_index 2 --time 5
../simulation.py --chi 239 --eigen_index 2 --time 5
../simulation.py --chi 240 --eigen_index 2 --time 5
../simulation.py --chi 241 --eigen_index 2 --time 5
../simulation.py --chi 242 --eigen_index 2 --time 5
../simulation.py --chi 243 --eigen_index 2 --time 5
../simulation.py --chi 244 --eigen_index 2 --time 5
../simulation.py --chi 245 --eigen_index 2 --time 5
../simulation.py --chi 246 --eigen_index 2 --time 5
../simulation.py --chi 247 --eigen_index 2 --time 5
../simulation.py --chi 248 --eigen_index 2 --time 5
../simulation.py --chi 249 --eigen_index 2 --time 5
../simulation.py --chi 250 --eigen_index 2 --time 5
../simulation.py --chi 251 --eigen_index 2 --time 5
../simulation.py --chi 252 --eigen_index 2 --time 5
../simulation.py --chi 253 --eigen_index 2 --time 5
../simulation.py --chi 254 --eigen_index 2 --time 5
../simulation.py --chi 255 --eigen_index 2 --time 5
../simulation.py --chi 256 --eigen_index 2 --time 5
../simulation.py --chi 257 --eigen_index 2 --time 5
../simulation.py --chi 258 --eigen_index 2 --time 5
../simulation.py --chi 259 --eigen_index 2 --time 5
../simulation.py --chi 260 --eigen_index 2 --time 5
../simulation.py --chi 261 --eigen_index 2 --time 5
../simulation.py --chi 262 --eigen_index 2 --time 5
../simulation.py --chi 263 --eigen_index 2 --time 5
../simulation.py --chi 264 --eigen_index 2 --time 5
../simulation.py --chi 265 --eigen_index 2 --time 5
../simulation.py --chi 266 --eigen_index 2 --time 5
../simulation.py --chi 267 --eigen_index 2 --time 5
../simulation.py --chi 268 --eigen_index 2 --time 5
../simulation.py --chi 269 --eigen_index 2 --time 5
../simulation.py --chi 270 --eigen_index 2 --time 5
../simulation.py --chi 271 --eigen_index 2 --time 5
../simulation.py --chi 272 --eigen_index 2 --time 5
../simulation.py --chi 273 --eigen_index 2 --time 5
../simulation.py --chi 274 --eigen_index 2 --time 5
../simulation.py --chi 275 --eigen_index 2 --time 5
../simulation.py --chi 276 --eigen_index 2 --time 5
../simulation.py --chi 277 --eigen_index 2 --time 5
../simulation.py --chi 278 --eigen_index 2 --time 5
../simulation.py --chi 279 --eigen_index 2 --time 5
../simulation.py --chi 280 --eigen_index 2 --time 5
../simulation.py --chi 281 --eigen_index 2 --time 5
../simulation.py --chi 282 --eigen_index 2 --time 5
../simulation.py --chi 283 --eigen_index 2 --time 5
../simulation.py --chi 284 --eigen_index 2 --time 5
../simulation.py --chi 285 --eigen_index 2 --time 5
../simulation.py --chi 286 --eigen_index 2 --time 5
../simulation.py --chi 287 --eigen_index 2 --time 5
../simulation.py --chi 288 --eigen_index 2 --time 5
../simulation.py --chi 289 --eigen_index 2 --time 5
../simulation.py --chi 290 --eigen_index 2 --time 5
../simulation.py --chi 291 --eigen_index 2 --time 5
../simulation.py --chi 292 --eigen_index 2 --time 5
../simulation.py --chi 293 --eigen_index 2 --time 5
../simulation.py --chi 294 --eigen_index 2 --time 5
../simulation.py --chi 295 --eigen_index 2 --time 5
../simulation.py --chi 296 --eigen_index 2 --time 5
../simulation.py --chi 297 --eigen_index 2 --time 5
../simulation.py --chi 298 --eigen_index 2 --time 5
../simulation.py --chi 299 --eigen_index 2 --time 5
../simulation.py --chi 300 --eigen_index 2 --time 5
../simulation.py --chi 301 --eigen_index 2 --time 5
../simulation.py --chi 302 --eigen_index 2 --time 5
../simulation.py --chi 303 --eigen_index 2 --time 5
../simulation.py --chi 304 --eigen_index 2 --time 5
../simulation.py --chi 305 --eigen_index 2 --time 5
../simulation.py --chi 306 --eigen_index 2 --time 5
../simulation.py --chi 307 --eigen_index 2 --time 5
../simulation.py --chi 308 --eigen_index 2 --time 5
../simulation.py --chi 309 --eigen_index 2 --time 5
../simulation.py --chi 310 --eigen_index 2 --time 5
../simulation.py --chi 311 --eigen_index 2 --time 5
../simulation.py --chi 312 --eigen_index 2 --time 5
../simulation.py --chi 313 --eigen_index 2 --time 5
../simulation.py --chi 314 --eigen_index 2 --time 5
../simulation.py --chi 315 --eigen_index 2 --time 5
../simulation.py --chi 316 --eigen_index 2 --time 5
../simulation.py --chi 317 --eigen_index 2 --time 5
../simulation.py --chi 318 --eigen_index 2 --time 5
../simulation.py --chi 319 --eigen_index 2 --time 5
../simulation.py --chi 320 --eigen_index 2 --time 5
../simulation.py --chi 321 --eigen_index 2 --time 5
../simulation.py --chi 322 --eigen_index 2 --time 5
../simulation.py --chi 323 --eigen_index 2 --time 5
../simulation.py --chi 324 --eigen_index 2 --time 5
../simulation.py --chi 325 --eigen_index 2 --time 5
../simulation.py --chi 326 --eigen_index 2 --time 5
../simulation.py --chi 327 --eigen_index 2 --time 5
../simulation.py --chi 328 --eigen_index 2 --time 5
../simulation.py --chi 329 --eigen_index 2 --time 5
../simulation.py --chi 330 --eigen_index 2 --time 5
../simulation.py --chi 331 --eigen_index 2 --time 5
../simulation.py --chi 332 --eigen_index 2 --time 5
../simulation.py --chi 333 --eigen_index 2 --time 5
../simulation.py --chi 334 --eigen_index 2 --time 5
../simulation.py --chi 335 --eigen_index 2 --time 5
../simulation.py --chi 336 --eigen_index 2 --time 5
../simulation.py --chi 337 --eigen_index 2 --time 5
../simulation.py --chi 338 --eigen_index 2 --time 5
../simulation.py --chi 339 --eigen_index 2 --time 5
../simulation.py --chi 340 --eigen_index 2 --time 5
../simulation.py --chi 341 --eigen_index 2 --time 5
../simulation.py --chi 342 --eigen_index 2 --time 5
../simulation.py --chi 343 --eigen_index 2 --time 5
../simulation.py --chi 344 --eigen_index 2 --time 5
../simulation.py --chi 345 --eigen_index 2 --time 5
../simulation.py --chi 346 --eigen_index 2 --time 5
../simulation.py --chi 347 --eigen_index 2 --time 5
../simulation.py --chi 348 --eigen_index 2 --time 5
../simulation.py --chi 349 --eigen_index 2 --time 5
../simulation.py --chi 350 --eigen_index 2 --time 5
../simulation.py --chi 351 --eigen_index 2 --time 5
../simulation.py --chi 352 --eigen_index 2 --time 5
../simulation.py --chi 353 --eigen_index 2 --time 5
../simulation.py --chi 354 --eigen_index 2 --time 5
../simulation.py --chi 355 --eigen_index 2 --time 5
../simulation.py --chi 356 --eigen_index 2 --time 5
../simulation.py --chi 357 --eigen_index 2 --time 5
../simulation.py --chi 358 --eigen_index 2 --time 5
../simulation.py --chi 359 --eigen_index 2 --time 5
../simulation.py --chi 360 --eigen_index 2 --time 5
../simulation.py --chi 361 --eigen_index 2 --time 5
../simulation.py --chi 362 --eigen_index 2 --time 5
../simulation.py --chi 363 --eigen_index 2 --time 5
../simulation.py --chi 364 --eigen_index 2 --time 5
../simulation.py --chi 365 --eigen_index 2 --time 5
../simulation.py --chi 366 --eigen_index 2 --time 5
../simulation.py --chi 367 --eigen_index 2 --time 5
../simulation.py --chi 368 --eigen_index 2 --time 5
../simulation.py --chi 369 --eigen_index 2 --time 5
../simulation.py --chi 370 --eigen_index 2 --time 5
../simulation.py --chi 371 --eigen_index 2 --time 5
../simulation.py --chi 372 --eigen_index 2 --time 5
../simulation.py --chi 373 --eigen_index 2 --time 5
../simulation.py --chi 374 --eigen_index 2 --time 5
../simulation.py --chi 375 --eigen_index 2 --time 5
../simulation.py --chi 376 --eigen_index 2 --time 5
../simulation.py --chi 377 --eigen_index 2 --time 5
../simulation.py --chi 378 --eigen_index 2 --time 5
../simulation.py --chi 379 --eigen_index 2 --time 5
../simulation.py --chi 380 --eigen_index 2 --time 5
../simulation.py --chi 381 --eigen_index 2 --time 5
../simulation.py --chi 382 --eigen_index 2 --time 5
../simulation.py --chi 383 --eigen_index 2 --time 5
../simulation.py --chi 384 --eigen_index 2 --time 5
../simulation.py --chi 385 --eigen_index 2 --time 5
../simulation.py --chi 386 --eigen_index 2 --time 5
../simulation.py --chi 387 --eigen_index 2 --time 5
../simulation.py --chi 388 --eigen_index 2 --time 5
../simulation.py --chi 389 --eigen_index 2 --time 5
../simulation.py --chi 390 --eigen_index 2 --time 5
../simulation.py --chi 391 --eigen_index 2 --time 5
../simulation.py --chi 392 --eigen_index 2 --time 5
../simulation.py --chi 393 --eigen_index 2 --time 5
../simulation.py --chi 394 --eigen_index 2 --time 5
../simulation.py --chi 395 --eigen_index 2 --time 5
../simulation.py --chi 396 --eigen_index 2 --time 5
../simulation.py --chi 397 --eigen_index 2 --time 5
../simulation.py --chi 398 --eigen_index 2 --time 5
../simulation.py --chi 399 --eigen_index 2 --time 5
../simulation.py --chi 400 --eigen_index 2 --time 5
../simulation.py --chi 401 --eigen_index 2 --time 5
../simulation.py --chi 402 --eigen_index 2 --time 5
../simulation.py --chi 403 --eigen_index 2 --time 5
../simulation.py --chi 404 --eigen_index 2 --time 5
../simulation.py --chi 405 --eigen_index 2 --time 5
../simulation.py --chi 406 --eigen_index 2 --time 5
../simulation.py --chi 407 --eigen_index 2 --time 5
../simulation.py --chi 408 --eigen_index 2 --time 5
../simulation.py --chi 409 --eigen_index 2 --time 5
../simulation.py --chi 410 --eigen_index 2 --time 5
../simulation.py --chi 411 --eigen_index 2 --time 5
../simulation.py --chi 412 --eigen_index 2 --time 5
../simulation.py --chi 413 --eigen_index 2 --time 5
../simulation.py --chi 414 --eigen_index 2 --time 5
../simulation.py --chi 415 --eigen_index 2 --time 5
../simulation.py --chi 416 --eigen_index 2 --time 5
../simulation.py --chi 417 --eigen_index 2 --time 5
../simulation.py --chi 418 --eigen_index 2 --time 5
../simulation.py --chi 419 --eigen_index 2 --time 5
../simulation.py --chi 420 --eigen_index 2 --time 5
../simulation.py --chi 421 --eigen_index 2 --time 5
../simulation.py --chi 422 --eigen_index 2 --time 5
../simulation.py --chi 423 --eigen_index 2 --time 5
../simulation.py --chi 424 --eigen_index 2 --time 5
../simulation.py --chi 425 --eigen_index 2 --time 5
../simulation.py --chi 426 --eigen_index 2 --time 5
../simulation.py --chi 427 --eigen_index 2 --time 5
../simulation.py --chi 428 --eigen_index 2 --time 5
../simulation.py --chi 429 --eigen_index 2 --time 5
../simulation.py --chi 430 --eigen_index 2 --time 5
../simulation.py --chi 431 --eigen_index 2 --time 5
../simulation.py --chi 432 --eigen_index 2 --time 5
../simulation.py --chi 433 --eigen_index 2 --time 5
../simulation.py --chi 434 --eigen_index 2 --time 5
../simulation.py --chi 435 --eigen_index 2 --time 5
../simulation.py --chi 436 --eigen_index 2 --time 5
../simulation.py --chi 437 --eigen_index 2 --time 5
../simulation.py --chi 438 --eigen_index 2 --time 5
../simulation.py --chi 439 --eigen_index 2 --time 5
../simulation.py --chi 440 --eigen_index 2 --time 5
../simulation.py --chi 441 --eigen_index 2 --time 5
../simulation.py --chi 442 --eigen_index 2 --time 5
../simulation.py --chi 443 --eigen_index 2 --time 5
../simulation.py --chi 444 --eigen_index 2 --time 5
../simulation.py --chi 445 --eigen_index 2 --time 5
../simulation.py --chi 446 --eigen_index 2 --time 5
../simulation.py --chi 447 --eigen_index 2 --time 5
../simulation.py --chi 448 --eigen_index 2 --time 5
../simulation.py --chi 449 --eigen_index 2 --time 5
../simulation.py --chi 450 --eigen_index 2 --time 5
../simulation.py --chi 451 --eigen_index 2 --time 5
../simulation.py --chi 452 --eigen_index 2 --time 5
../simulation.py --chi 453 --eigen_index 2 --time 5
../simulation.py --chi 454 --eigen_index 2 --time 5
../simulation.py --chi 455 --eigen_index 2 --time 5
../simulation.py --chi 456 --eigen_index 2 --time 5
../simulation.py --chi 457 --eigen_index 2 --time 5
../simulation.py --chi 458 --eigen_index 2 --time 5
../simulation.py --chi 459 --eigen_index 2 --time 5
../simulation.py --chi 460 --eigen_index 2 --time 5
../simulation.py --chi 461 --eigen_index 2 --time 5
../simulation.py --chi 462 --eigen_index 2 --time 5
../simulation.py --chi 463 --eigen_index 2 --time 5
../simulation.py --chi 464 --eigen_index 2 --time 5
../simulation.py --chi 465 --eigen_index 2 --time 5
../simulation.py --chi 466 --eigen_index 2 --time 5
../simulation.py --chi 467 --eigen_index 2 --time 5
../simulation.py --chi 468 --eigen_index 2 --time 5
../simulation.py --chi 469 --eigen_index 2 --time 5
../simulation.py --chi 470 --eigen_index 2 --time 5
../simulation.py --chi 471 --eigen_index 2 --time 5
../simulation.py --chi 472 --eigen_index 2 --time 5
../simulation.py --chi 473 --eigen_index 2 --time 5
../simulation.py --chi 474 --eigen_index 2 --time 5
../simulation.py --chi 475 --eigen_index 2 --time 5
../simulation.py --chi 476 --eigen_index 2 --time 5
../simulation.py --chi 477 --eigen_index 2 --time 5
../simulation.py --chi 478 --eigen_index 2 --time 5
../simulation.py --chi 479 --eigen_index 2 --time 5
../simulation.py --chi 480 --eigen_index 2 --time 5
../simulation.py --chi 481 --eigen_index 2 --time 5
../simulation.py --chi 482 --eigen_index 2 --time 5
../simulation.py --chi 483 --eigen_index 2 --time 5
../simulation.py --chi 484 --eigen_index 2 --time 5
../simulation.py --chi 485 --eigen_index 2 --time 5
../simulation.py --chi 486 --eigen_index 2 --time 5
../simulation.py --chi 487 --eigen_index 2 --time 5
../simulation.py --chi 488 --eigen_index 2 --time 5
../simulation.py --chi 489 --eigen_index 2 --time 5
../simulation.py --chi 490 --eigen_index 2 --time 5
../simulation.py --chi 491 --eigen_index 2 --time 5
../simulation.py --chi 492 --eigen_index 2 --time 5
../simulation.py --chi 493 --eigen_index 2 --time 5
../simulation.py --chi 494 --eigen_index 2 --time 5
../simulation.py --chi 495 --eigen_index 2 --time 5
../simulation.py --chi 496 --eigen_index 2 --time 5
../simulation.py --chi 497 --eigen_index 2 --time 5
../simulation.py --chi 498 --eigen_index 2 --time 5
../simulation.py --chi 499 --eigen_index 2 --time 5
../simulation.py --chi 500 --eigen_index 2 --time 5
../simulation.py --chi 501 --eigen_index 2 --time 5
../simulation.py --chi 502 --eigen_index 2 --time 5
../simulation.py --chi 503 --eigen_index 2 --time 5
../simulation.py --chi 504 --eigen_index 2 --time 5
../simulation.py --chi 505 --eigen_index 2 --time 5
../simulation.py --chi 506 --eigen_index 2 --time 5
../simulation.py --chi 507 --eigen_index 2 --time 5
../simulation.py --chi 508 --eigen_index 2 --time 5
../simulation.py --chi 509 --eigen_index 2 --time 5
../simulation.py --chi 510 --eigen_index 2 --time 5
../simulation.py --chi 511 --eigen_index 2 --time 5
../simulation.py --chi 512 --eigen_index 2 --time 5
../simulation.py --chi 513 --eigen_index 2 --time 5
../simulation.py --chi 514 --eigen_index 2 --time 5
../simulation.py --chi 515 --eigen_index 2 --time 5
../simulation.py --chi 516 --eigen_index 2 --time 5
../simulation.py --chi 517 --eigen_index 2 --time 5
../simulation.py --chi 518 --eigen_index 2 --time 5
../simulation.py --chi 519 --eigen_index 2 --time 5
../simulation.py --chi 520 --eigen_index 2 --time 5
../simulation.py --chi 521 --eigen_index 2 --time 5
../simulation.py --chi 522 --eigen_index 2 --time 5
../simulation.py --chi 523 --eigen_index 2 --time 5
../simulation.py --chi 524 --eigen_index 2 --time 5
../simulation.py --chi 525 --eigen_index 2 --time 5
../simulation.py --chi 526 --eigen_index 2 --time 5
../simulation.py --chi 527 --eigen_index 2 --time 5
../simulation.py --chi 528 --eigen_index 2 --time 5
../simulation.py --chi 529 --eigen_index 2 --time 5
../simulation.py --chi 530 --eigen_index 2 --time 5
../simulation.py --chi 531 --eigen_index 2 --time 5
../simulation.py --chi 532 --eigen_index 2 --time 5
../simulation.py --chi 533 --eigen_index 2 --time 5
../simulation.py --chi 534 --eigen_index 2 --time 5
../simulation.py --chi 535 --eigen_index 2 --time 5
../simulation.py --chi 536 --eigen_index 2 --time 5
../simulation.py --chi 537 --eigen_index 2 --time 5
../simulation.py --chi 538 --eigen_index 2 --time 5
../simulation.py --chi 539 --eigen_index 2 --time 5
../simulation.py --chi 540 --eigen_index 2 --time 5
../simulation.py --chi 541 --eigen_index 2 --time 5
../simulation.py --chi 542 --eigen_index 2 --time 5
../simulation.py --chi 543 --eigen_index 2 --time 5
../simulation.py --chi 544 --eigen_index 2 --time 5
../simulation.py --chi 545 --eigen_index 2 --time 5
../simulation.py --chi 546 --eigen_index 2 --time 5
../simulation.py --chi 547 --eigen_index 2 --time 5
../simulation.py --chi 548 --eigen_index 2 --time 5
../simulation.py --chi 549 --eigen_index 2 --time 5
../simulation.py --chi 550 --eigen_index 2 --time 5
../simulation.py --chi 551 --eigen_index 2 --time 5
../simulation.py --chi 552 --eigen_index 2 --time 5
../simulation.py --chi 553 --eigen_index 2 --time 5
../simulation.py --chi 554 --eigen_index 2 --time 5
../simulation.py --chi 555 --eigen_index 2 --time 5
../simulation.py --chi 556 --eigen_index 2 --time 5
../simulation.py --chi 557 --eigen_index 2 --time 5
../simulation.py --chi 558 --eigen_index 2 --time 5
../simulation.py --chi 559 --eigen_index 2 --time 5
../simulation.py --chi 560 --eigen_index 2 --time 5
../simulation.py --chi 561 --eigen_index 2 --time 5
../simulation.py --chi 562 --eigen_index 2 --time 5
../simulation.py --chi 563 --eigen_index 2 --time 5
../simulation.py --chi 564 --eigen_index 2 --time 5
../simulation.py --chi 565 --eigen_index 2 --time 5
../simulation.py --chi 566 --eigen_index 2 --time 5
../simulation.py --chi 567 --eigen_index 2 --time 5
../simulation.py --chi 568 --eigen_index 2 --time 5
../simulation.py --chi 569 --eigen_index 2 --time 5
../simulation.py --chi 570 --eigen_index 2 --time 5
../simulation.py --chi 571 --eigen_index 2 --time 5
../simulation.py --chi 572 --eigen_index 2 --time 5
../simulation.py --chi 573 --eigen_index 2 --time 5
../simulation.py --chi 574 --eigen_index 2 --time 5
../simulation.py --chi 575 --eigen_index 2 --time 5
../simulation.py --chi 576 --eigen_index 2 --time 5
../simulation.py --chi 577 --eigen_index 2 --time 5
../simulation.py --chi 578 --eigen_index 2 --time 5
../simulation.py --chi 579 --eigen_index 2 --time 5
../simulation.py --chi 580 --eigen_index 2 --time 5
../simulation.py --chi 581 --eigen_index 2 --time 5
../simulation.py --chi 582 --eigen_index 2 --time 5
../simulation.py --chi 583 --eigen_index 2 --time 5
../simulation.py --chi 584 --eigen_index 2 --time 5
../simulation.py --chi 585 --eigen_index 2 --time 5
../simulation.py --chi 586 --eigen_index 2 --time 5
../simulation.py --chi 587 --eigen_index 2 --time 5
../simulation.py --chi 588 --eigen_index 2 --time 5
../simulation.py --chi 589 --eigen_index 2 --time 5
../simulation.py --chi 590 --eigen_index 2 --time 5
../simulation.py --chi 591 --eigen_index 2 --time 5
../simulation.py --chi 592 --eigen_index 2 --time 5
../simulation.py --chi 593 --eigen_index 2 --time 5
../simulation.py --chi 594 --eigen_index 2 --time 5
../simulation.py --chi 595 --eigen_index 2 --time 5
../simulation.py --chi 596 --eigen_index 2 --time 5
../simulation.py --chi 597 --eigen_index 2 --time 5
../simulation.py --chi 598 --eigen_index 2 --time 5
../simulation.py --chi 599 --eigen_index 2 --time 5
