name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # if you don't have requirements.txt yet
          pip install pylint

      - name: Run Pylint
        run: |
          source venv/bin/activate
          files=$(find . -name '*.py')
          if [ -n "$files" ]; then
            python -m pylint $files
          else
            echo "No Python files found to lint"
          fi
